mybatis:
  mapper-locations: classpath:com/practice/biztech/mix/dal/**/*.xml

spring:
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/world
    type: com.zaxxer.hikari.HikariDataSource
    password: root
    username: root
    hikari:
      pool-name: hikari-pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
  redis:
    cluster:
      nodes: localhost:6379
